export const CLEAR_ITEMS_LIST = 'CLEAR_ITEMS_LIST';
export const DATA_LOAD_FAILED = 'DATA_LOAD_FAILED';
export const DATA_LOAD_SUCCESS = 'DATA_LOAD_SUCCESS';
export const DATA_LOAD_INITIATED = 'DATA_LOAD_INITIATED';
